name: sensory_alarm
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cloud_firestore: ^4.14.0
  # flutter_blue_plus: ^1.31.15
  esp_smartconfig: ^1.1.11
  http: ^1.2.0
  flutter_bluetooth_serial: ^0.4.0
  uuid: ^4.3.3
  audioplayers: ^6.0.0
  firebase_messaging: ^14.9.2
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true